# --- CONFIGURATION SERVEUR ---
server.port=8080
spring.application.name=treep-backend

# --- CONFIGURATION BASE DE DONNÉES ---
# Par défaut sur localhost pour le dev (IntelliJ/Eclipse).
# Docker remplacera automatiquement ça par "db" grâce au docker-compose.
spring.datasource.url=jdbc:postgresql://localhost:5432/treepdb
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# --- CONFIGURATION JPA (HIBERNATE) ---
spring.jpa.database=POSTGRESQL

# C'est cette ligne qui crée les tables automatiquement (Voyage, Activite)
spring.jpa.hibernate.ddl-auto=update

# Permet l'initialisation des données
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Affiche le SQL dans la console (pour le debug)
spring.jpa.show-sql=true

# Spécificités du dialecte Postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# --- CONFIGURATION JSON ---
# Gestion propre des dates (2023-12-09 au lieu de timestamps illisibles)
spring.jackson.serialization.write-dates-as-timestamps=false